export let category = [
  "Adventure",
  "Romantic",
  "Historical",
  "City Tour",
  "Leisure",
  "Cultural",
  "Luxury"
]
export let data = [
  {
    "id": 1,
    "destination": "Paris",
    "country": "France",
    "price": 5200,
    "duration": 5,
    "category": "Romantic",
    "rating": 4.8,
    "description": "Experience the city of love with guided tours and Seine river cruises.",
    "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    "about": "Paris, the capital city of France, is known for its art, fashion, gastronomy, and culture. The city is famous for its iconic landmarks such as the Eiffel Tower, Louvre Museum, and Notre- Dame Cathedral.It is a popular destination for couples and travelers seeking romance and adventure.lorem ipsum dolor sit amet consectetur adipisicing elit.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.",
      
    },


{
  "id": 2,
    "destination": "Tokyo",
      "country": "Japan",
        "price": 4500,
          "duration": 7,
            "category": "Adventure",
              "rating": 4.7,
                "description": "Explore the vibrant culture, ancient temples, and futuristic cityscapes.",
                  "image_url": "https://th.bing.com/th/id/OIP.8N-X97_912oG_Vkp2zBSBgHaE1?w=286&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Tokyo is the capital city of Japan and is known for its blend of traditional and modern culture. The city offers a unique experience with its ancient temples, bustling streets, and cutting-edge technology. It is a must-visit destination for travelers seeking adventure and cultural immersion. lorem ipsum dolor sit amet consectetur adipisicing elit.  Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.",
 
},
{
  "id": 3,
    "destination": "Bali",
      "country": "Indonesia",
        "price": 9000,
          "duration": 6,
            "category": "Leisure",
              "rating": 4.9,
                "description": "Relax on beautiful beaches and experience rich Balinese culture.",
                  "image_url": "https://th.bing.com/th/id/OIP.G_cWlENJG0fpod6YMeqwhAHaE8?w=272&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. It is a popular destination for tourists seeking relaxation, adventure, and cultural experiences.The island offers a unique blend of natural beauty and rich traditions.lorem ipsum dolor sit amet consectetur adipisicing elit.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.Quisquam, voluptatibus.",
      
},
{
  "id": 4,
    "destination": "New York",
      "country": "USA",
        "price": 11400,
          "duration": 5,
            "category": "City Tour",
              "rating": 4.6,
                "description": "Visit iconic landmarks like Times Square, Central Park, and the Statue of Liberty.",
                  "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                    "about": "New York City, often simply called New York, is the most populous city in the United States. It is known for its significant impact on commerce, culture, fashion, and finance. The city is home to iconic landmarks such as the Statue of Liberty, Central Park, and Times Square. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus  Quisquam, voluptatibus.Quisquam, voluptatibus.",
 
},
{
  "id": 5,
    "destination": "Cairo",
      "country": "Egypt",
        "price": 11000,
          "duration": 6,
            "category": "Historical",
              "rating": 4.5,
                "description": "Discover the ancient pyramids and the mysteries of the Sphinx.",
                  "image_url": "https://th.bing.com/th/id/OIP.7BLuKWCbxtDDYMr8qeXFpAHaE8?w=227&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Cairo is the capital of Egypt and is known for its rich history and vibrant culture. It is home to some of the world's most famous ancient monuments, including the Pyramids of Giza and the Sphinx. The city offers a unique blend of ancient and modern attractions, making it a fascinating destination for travelers. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
    },
{
  "id": 6,
    "destination": "Maldives",
      "country": "Maldives",
        "price": 9000,
          "duration": 5,
            "category": "Luxury",
              "rating": 4.9,
                "description": "Enjoy white sandy beaches, crystal-clear water, and luxury resorts.",
                  "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?crop=entropy&cs=tinysrgb&fit=crop&w=800&q=80",
                    "about": "The Maldives is a tropical paradise known for its stunning beaches, crystal-clear waters, and luxurious resorts. It is a popular destination for honeymooners and those seeking relaxation and adventure in a beautiful setting. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 7,
    "destination": "Dubai",
      "country": "UAE",
        "price": 17100,
          "duration": 6,
            "category": "City Tour",
              "rating": 4.8,
                "description": "Explore the luxurious malls, Burj Khalifa, desert safari and modern wonders.",
                  "image_url": "https://th.bing.com/th/id/OIP.KNnr7tn-4LuTlgmpp2dZEwHaDt?w=302&h=175&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Dubai is a city in the United Arab Emirates known for its modern architecture, luxury shopping, and vibrant nightlife. It is home to the Burj Khalifa, the tallest building in the world, and offers a mix of traditional culture and contemporary attractions. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 8,
    "destination": "Rome",
      "country": "Italy",
        "price": 10300,
          "duration": 5,
            "category": "Historical",
              "rating": 4.7,
                "description": "Step back in time with the Colosseum, Roman Forum, and Vatican City tours.",
                  "image_url": "https://th.bing.com/th/id/OIP.kHKMa4NGBErM8pw2JTpX2wHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Rome, the capital city of Italy, is known for its nearly 3,000 years of globally influential art, architecture and culture. The city is home to the Vatican City, the seat of the Roman Catholic Church, and is filled with ancient ruins such as the Colosseum and the Roman Forum. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 9,
    "destination": "London",
      "country": "UK",
        "price": 10400,
          "duration": 5,
            "category": "City Tour",
              "rating": 4.6,
                "description": "Visit Big Ben, the London Eye, Buckingham Palace and more.",
                  "image_url": "https://th.bing.com/th/id/OIP.TKRumbBwMjCn3a8uS1kVjgHaEJ?w=284&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "London is the capital city of England and the United Kingdom. It is a leading global city known for its history, culture, and influence in various fields. The city is home to iconic landmarks such as the Tower of London, Buckingham Palace, and the British Museum. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 10,
    "destination": "Santorini",
      "country": "Greece",
        "price": 16020,
          "duration": 6,
            "category": "Romantic",
              "rating": 4.9,
                "description": "Breathtaking sunsets, white-washed houses, and crystal-clear waters await.",
                  "image_url": "https://th.bing.com/th/id/OIP.NLiLeW_d0I4lt2N1uSslmwHaEK?w=276&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Santorini is a beautiful island in Greece known for its stunning sunsets, white-washed buildings, and crystal-clear waters. It is a popular destination for couples and honeymooners. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 11,
    "destination": "Sydney",
      "country": "Australia",
        "price": 18000,
          "duration": 7,
            "category": "Adventure",
              "rating": 4.7,
                "description": "Explore the Sydney Opera House, Bondi Beach, and the Harbour Bridge.",
                  "image_url": "https://th.bing.com/th/id/OIP.7kf3B55HVhxV1UlLG6b1XwHaE6?w=275&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Sydney is a vibrant city known for its iconic landmarks, beautiful beaches, and diverse culture. It offers a mix of urban experiences and natural beauty, making it a popular destination for travelers. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 12,
    "destination": "Iceland",
      "country": "Iceland",
        "price": 20000,
          "duration": 8,
            "category": "Adventure",
              "rating": 4.8,
                "description": "Experience the Northern Lights, geysers, and stunning landscapes.",
                  "image_url": "https://th.bing.com/th/id/OIP.esVdHvkhTMobwSe_FOTJjAHaE8?w=286&h=191&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Iceland is a Nordic island country known for its stunning natural beauty, including geysers, hot springs, waterfalls, and glaciers. It is a popular destination for adventure seekers and nature lovers. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 13,
    "destination": "Barcelona",
      "country": "Spain",
        "price": 12000,
          "duration": 5,
            "category": "Cultural",
              "rating": 4.6,
                "description": "Discover Gaudi's masterpieces, vibrant culture, and beautiful beaches.",
                  "image_url": "https://th.bing.com/th/id/OIP.5LU_Lbtlyot95uvDeu6zRgHaEj?w=315&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Barcelona is a city in Spain known for its art and architecture. The fantastical Sagrada Família church and other modernist landmarks designed by Antoni Gaudí dot the city. It is a vibrant destination with a rich cultural heritage. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 14,
    "destination": "Amsterdam",
      "country": "Netherlands",
        "price": 11000,
          "duration": 5,
            "category": "Cultural",
              "rating": 4.7,
                "description": "Explore the canals, museums, and vibrant culture of this beautiful city.",
                  "image_url": "https://th.bing.com/th/id/OIP.A9myHlnXIswrQ-2dpBD7SAHaE8?w=279&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Amsterdam is the capital city of the Netherlands, known for its artistic heritage, elaborate canal system, and narrow houses with gabled facades. It is a popular destination for travelers seeking culture and history. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 15,
    "destination": "Bangkok",
      "country": "Thailand",
        "price": 8000,
          "duration": 6,
            "category": "Adventure",
              "rating": 4.5,
                "description": "Experience the vibrant street life and cultural landmarks.",
                  "image_url": "https://th.bing.com/th/id/OIP.E42xVq2-McQfrl5ebXkDqwHaDT?w=295&h=155&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Bangkok is the capital city of Thailand and is known for its vibrant street life and cultural landmarks. The city is famous for its ornate shrines and vibrant nightlife. It is a popular destination for travelers seeking adventure and cultural experiences. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },
{
  "id": 16,
    "destination": "Rio de Janeiro",
      "country": "Brazil",
        "price": 9500,
          "duration": 7,
            "category": "Adventure",
              "rating": 4.8,
                "description": "Experience the vibrant culture, beaches, and Carnival festival.",
                  "image_url": "https://th.bing.com/th/id/OIP.kHKMa4NGBErM8pw2JTpX2wHaFj?w=204&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                    "about": "Rio de Janeiro is a vibrant city in Brazil known for its Copacabana and Ipanema beaches, Sugarloaf Mountain, and the Christ the Redeemer statue. It is famous for its Carnival festival and lively culture. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus. Quisquam, voluptatibus.",
        },

      
  ]









